# INPUT DATA DIRECTORY
fastq_dir: "/maps/projects/renlab/people/qgr178/Projects/AGO1/Data"

# REFERENCE FILES
genome_fasta: "/maps/projects/renlab/people/qgr178/Shared/Reference/A_thaliana/TAIR10/TAIR10_chr_all_withADAR.fas"
transcriptome_fasta: "/maps/projects/renlab/people/qgr178/Shared/Reference/A_thaliana/Araport11/Araport11_cdna_20220914_withADAR.fa"
genome_gtf: "/maps/projects/renlab/people/qgr178/Shared/Reference/A_thaliana/Araport11/Araport11_GTF_genes_transposons.20241001_withADAR.gtf"

# STAR PARAMETERS
star_index_dir: "/maps/projects/renlab/people/qgr178/Shared/Reference/A_thaliana/Araport11/index_STAR_ADAR" # will be created if doesn't exist
star_sjdbOverhang: 143
star_genomeSAindexNbases: 12
sjdb_file: ""  # now empty

# SALMON PARAMETERS
salmon_index_dir: "/maps/projects/renlab/people/qgr178/Shared/Reference/A_thaliana/Araport11/index_salmon_ADAR" # will be created if doesn't exist
salmon_threads: 6

# OUTPUT DIRECTORY
results_dir: "/maps/projects/renlab/people/qgr178/Projects/AGO1/Results"

# R1 suffix (R2 will be automatically deduced by replacing 1 with 2)
r1_suffix: "_1P.fq.gz"  